- ros_topic_name: "lidar_3d/scan"
  gz_topic_name: "/world/indoor_room/model/x500_test_0/link/lidar3d_link/sensor/lidar_3d/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: "GZ_TO_ROS"

- ros_topic_name: "lidar_3d/points"
  gz_topic_name: "/world/indoor_room/model/x500_test_0/link/lidar3d_link/sensor/lidar_3d/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

- ros_topic_name: "depth_camera/image"
  gz_topic_name: "/depth_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "depth_camera/points"
  gz_topic_name: "/depth_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"
